"""add email to doctor

Revision ID: 15e7caf2d17a
Revises: 
Create Date: 2018-09-20 16:32:03.027720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e7caf2d17a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.drop_index('doctor_email_uindex', table_name='doctor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('doctor_email_uindex', 'doctor', ['email'], unique=True)
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    # ### end Alembic commands ###
