"""relationships

Revision ID: 1a3f9efe39f1
Revises: 
Create Date: 2018-09-17 16:28:37.092232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3f9efe39f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment', sa.DateTime(), nullable=True),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(length=200), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor.doctorId'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('medication', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultationId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('additionalNotes', sa.String(length=300), nullable=True),
    sa.Column('symptoms', sa.String(length=120), nullable=True),
    sa.Column('diagnosis', sa.String(length=120), nullable=True),
    sa.Column('actualStart', sa.DateTime(), nullable=True),
    sa.Column('actualEnd', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultationId'], ['consultation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_details')
    op.drop_table('medication')
    op.drop_table('consultation')
    op.drop_table('condition')
    # ### end Alembic commands ###
