"""doctors table

Revision ID: 9d7d47019724
Revises: 
Create Date: 2018-09-20 18:13:21.199450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7d47019724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_column('doctor', 'email')
    # ### end Alembic commands ###
